suttacentral/publications

tests/test_sources.py

- Fix path for finding sources

Fix path for finding sources

---

templates/README.md
templates/blurb-example.html
templates/blurb-template.html
templates/book-template.html
templates/colophon.html
templates/halftitle-page-template.html
templates/imprint-template.html
templates/main-toc.html
templates/secondary-toc.html
templates/title-page-template.html

Merging these templates so that we don't need to download them from GitHub in our application but instead read them from local files.

Sujato templates

---

.env_public
sutta_publisher/src/sutta_publisher/edition_parsers/base.py
sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py
sutta_publisher/src/sutta_publisher/shared/config.py
sutta_publisher/src/sutta_publisher/shared/data.py
sutta_publisher/src/sutta_publisher/shared/value_objects/edition_config.py
sutta_publisher/src/sutta_publisher/shared/value_objects/edition_data.py
sutta_publisher/src/sutta_publisher/shared/value_objects/parser_objects.py
sutta_publisher/src/sutta_publisher/templates/endnotes-template.html

- add endnotes section to backmatter
- add note references inside main text
- fix creating the last chapter titles in main texts
- add exception handling if creator's biography is not found
- Receive service payloads
- Push them to relevant handler

Add endnotes to html

---

.env_public
sutta_publisher/src/sutta_publisher/edition_parsers/base.py
sutta_publisher/src/sutta_publisher/shared/value_objects/parser_objects.py
sutta_publisher/src/sutta_publisher/templates/endnotes-template.html

- change "notes" matter name to "endnotes"

Update endnotes matter name

---

sutta_publisher/src/sutta_publisher/edition_parsers/base.py
sutta_publisher/src/sutta_publisher/edition_parsers/epub.py
sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py
sutta_publisher/src/sutta_publisher/edition_parsers/html.py
sutta_publisher/tests/unit/test_helper_functions.py

- Add removing empty tags from mainmatter
- Add handling additional cases with reference links
- Update test cases

Html remove empty tags

---

sutta_publisher/src/sutta_publisher/edition_parsers/base.py
sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py
sutta_publisher/tests/unit/test_helper_functions.py

- Add node validation which raises SystemExit if node is incorrect

Node validator

---

README.md

Removes extra backtick, changes "features" header to "requirements," and fixes `make make lint` to `make lint`.

docs: fix readme issues

---

sutta_publisher/src/sutta_publisher/edition_parsers/base.py
sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py
sutta_publisher/src/sutta_publisher/edition_parsers/html.py
sutta_publisher/src/sutta_publisher/shared/value_objects/edition_config.py
sutta_publisher/src/sutta_publisher/shared/value_objects/parser_objects.py
sutta_publisher/src/sutta_publisher/templates/book-template.html
sutta_publisher/src/sutta_publisher/templates/imprint-template.html
sutta_publisher/tests/unit/test_helper_functions.py

- fix nesting ToC lists
- fix pretty printing of dt and dd tags
- fix getting uids for html body tags
- replace span tags with br tags for verses
- add publication's url to imprint
- hardcode adding uids to samyutta headings in SN
- fix epub ToC titles

2496 remaining bugs

---

sutta_publisher/src/sutta_publisher/edition_parsers/epub.py

- [EPUB] Link default style sheet to all chapters

Fix epub css

---

sutta_publisher/src/sutta_publisher/edition_parsers/pdf.py
sutta_publisher/src/sutta_publisher/templates/tex/epigraph-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/halftitle-page-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/heading-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/imprint-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/preamble-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/title-page-template.tex
sutta_publisher/tests/unit/test_pdf_edition.py

- Refactor appending epigraph after API changes
- Add tests for translating html into tex
- Fix adding chapters when heading contains inner tags

Latex refactor epigraph

---

.env_public
sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py
sutta_publisher/src/sutta_publisher/edition_parsers/latex.py
sutta_publisher/src/sutta_publisher/edition_parsers/paperback.py

- Fix getting translation title for additional part headings in case of multiple volumes
- Refactor node validator
- Adjust variable names

Adjustment of additional part headings, refactor node validator

---

.github/pull_request_template.md
sutta_publisher/src/sutta_publisher/edition_parsers/latex.py
sutta_publisher/src/sutta_publisher/edition_parsers/paperback.py
sutta_publisher/src/sutta_publisher/edition_parsers/pdf.py
sutta_publisher/tests/unit/test_latex_parser.py

- Fix appending part title in DN and PVR
- Update PR description template

121 fix appending part title in dn pvr

---

sutta_publisher/src/sutta_publisher/edition_parsers/base.py
sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py
sutta_publisher/src/sutta_publisher/edition_parsers/latex.py
sutta_publisher/src/sutta_publisher/shared/data.py
sutta_publisher/src/sutta_publisher/shared/value_objects/edition_data.py
sutta_publisher/src/sutta_publisher/shared/value_objects/parser_objects.py
sutta_publisher/tests/unit/test_latex_parser.py

- Add support for thematic breaks
- Refactor inserting preheadings (using depths from structure tree)
- Remove reduntant code

[WIP] Add thematic breaks, refactor inserting preheadings

---

.github/workflows/publisher_test.yml
.github/workflows/run_publisher.yml
sutta_publisher/src/sutta_publisher/shared/github_handler.py
sutta_publisher/tests/unit/test_github_handler.py

- Update workflows yml,
- Add error message,
- Update tests

Update workflows yml, add error message, update tests

---

.env_public
Makefile
sutta_publisher/src/sutta_publisher/main.py
sutta_publisher/src/sutta_publisher/shared/__init__.py
sutta_publisher/src/sutta_publisher/shared/config.py
sutta_publisher/src/sutta_publisher/shared/data.py
sutta_publisher/src/sutta_publisher/shared/edition_finder.py
sutta_publisher/src/sutta_publisher/shared/github_handler.py
sutta_publisher/src/sutta_publisher/shared/publisher.py
sutta_publisher/src/sutta_publisher/shared/value_objects/base.py
sutta_publisher/src/sutta_publisher/shared/value_objects/edition_config.py
sutta_publisher/tests/conftest.py
sutta_publisher/tests/unit/test_config.py
sutta_publisher/tests/unit/test_edition_finder.py
sutta_publisher/tests/unit/test_github_handler.py

- Add support for getting publications that were modified since last run

GitHub actions find modified publications

---

.github/workflows/auto_run_publisher.yml
.github/workflows/run_publisher.yml
sutta_publisher/src/sutta_publisher/shared/github_handler.py

- Add periodic run of SuttaPublisher
- Add a 'force' flag when updating git's remote ref
- Add an Auth Token to all GitHub api GET requests
- Minor code improvements

Run periodic GitHub actions

---

.env_public
.github/workflows/test.yml
sutta_publisher/src/sutta_publisher/edition_parsers/latex.py
sutta_publisher/src/sutta_publisher/main.py
sutta_publisher/src/sutta_publisher/shared/config.py
sutta_publisher/src/sutta_publisher/shared/edition_finder.py
sutta_publisher/src/sutta_publisher/shared/value_objects/edition_config.py
sutta_publisher/tests/unit/test_config.py

- Add support for frontmatter endnotes

Add support for frontmatter endnotes

---

sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py

- Fix getting chapter names for epub edition

Fix getting chapter names

---

.env_public
.github/workflows/test.yml
sutta_publisher/src/sutta_publisher/edition_parsers/latex.py
sutta_publisher/src/sutta_publisher/main.py
sutta_publisher/src/sutta_publisher/shared/__init__.py
sutta_publisher/src/sutta_publisher/shared/edition_finder.py
sutta_publisher/src/sutta_publisher/shared/github_handler.py
sutta_publisher/src/sutta_publisher/templates/html/endnotes-template.html
sutta_publisher/src/sutta_publisher/templates/tex/cover/paperback-cover-body-template.tex

- Add support for clickable links in pdf
- Add support for custom backmatter endnotes
- Refactor saving info about last run

Stretch goals

---

sutta_publisher/src/sutta_publisher/edition_parsers/base.py
sutta_publisher/src/sutta_publisher/edition_parsers/latex.py
sutta_publisher/tests/unit/test_latex_parser.py

Disambiguate pannasaka

---

sutta_publisher/src/sutta_publisher/edition_parsers/latex.py
sutta_publisher/tests/unit/test_latex_parser.py

Add support for uddanagatha

---

.env_public
sutta_publisher/src/sutta_publisher/templates/tex/shared/preamble-template.tex

- Add support for expansion text

Add support for expansion text

---

sutta_publisher/Dockerfile
sutta_publisher/docker_entrypoint.sh
sutta_publisher/src/sutta_publisher/edition_parsers/helper_functions.py
sutta_publisher/src/sutta_publisher/templates/tex/shared/imprint-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/shared/metadata-template.xmpdata

- Add updating project files inside the container on each app run
- Improve the way of copying fonts to the container
- Move the result .xmpdata files to the .zip file with all source files
- Fix imprint links in the paperback edition
- Fix .xmpdata date error (PDF/A-3u)

Add updating project files on app run, minor fixes

---

sutta_publisher/src/sutta_publisher/edition_parsers/latex.py

- Add images_directory variable to colophon template

Add images directory to colophon template

---

sutta_publisher/src/sutta_publisher/templates/tex/shared/preamble-template.tex

call pdfx at start per recommendation

---

sutta_publisher/src/sutta_publisher/edition_parsers/__init__.py
sutta_publisher/src/sutta_publisher/edition_parsers/hardcover.py
sutta_publisher/src/sutta_publisher/main.py
sutta_publisher/src/sutta_publisher/templates/tex/cover/hardcover-cover-body-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/cover/hardcover-cover-preamble-template.tex

Added the function of generating hardcover version.

Added the function of generating hardcover version.

---

sutta_publisher/src/sutta_publisher/edition_parsers/hardcover.py

Remove test code.

---

sutta_publisher/src/sutta_publisher/templates/tex/cover/hardcover-cover-body-template.tex

Adjust spin total width and vol number width.

Adjust spin total width and vol number width.

---

sutta_publisher/src/sutta_publisher/edition_parsers/latex.py

Do not display footnote when generating hardcover version.

Do not display footnote when generating hardcover version.

---

sutta_publisher/src/sutta_publisher/templates/tex/cover/hardcover-cover-body-template.tex

Adjust the cover of hardcover version.

Adjust the cover of hardcover version.

---

sutta_publisher/src/sutta_publisher/edition_parsers/latex.py

Disable conversion of Pali text on cover

Disable conversion of Pali text on cover

---

sutta_publisher/src/sutta_publisher/templates/tex/shared/preamble-template.tex

Adjust the pagesize.

---

sutta_publisher/src/sutta_publisher/templates/tex/shared/epigraph-template.tex
sutta_publisher/src/sutta_publisher/templates/tex/shared/preamble-template.tex

Adjust the pagesize and map position.

Adjust the pagesize and map position.
